using System;
namespace BarberShop.BL.DTOs.ViewModel
{
    public class productosViewModel : BaseViewModel
    {
        public string productid { get; set; }
        public string refmercmae { get; set; }
        public string codigoalte { get; set; }
        public string desmercmae { get; set; }
        public string medidaid { get; set; }
        public string framercmae { get; set; }
        public string suplidorid { get; set; }
        public string dptoid { get; set; }
        public string familiaid { get; set; }
        public string fngrafico { get; set; }
        public string impuestoid { get; set; }
        public double timercmae { get; set; }
        public int blcnega { get; set; }
        public int serialid { get; set; }
        public int ensamble { get; set; }
        public int vtammini { get; set; }
        public int difmedidas { get; set; }
        public int itbis { get; set; }
        public int caduce { get; set; }
        public int cabecera { get; set; }
        public string tipo { get; set; }
        public string codigocab { get; set; }
        public int invlotes { get; set; }
        public int calcular_prc { get; set; }
        public int invetario { get; set; }
        public double precventa { get; set; }
        public double precespeci { get; set; }
        public double precminimo { get; set; }
        public double costoprome { get; set; }
        public double costocompr { get; set; }
        public double costodolla { get; set; }
        public double porcprc1 { get; set; }
        public double porcprc2 { get; set; }
        public double porcprc3 { get; set; }
        public double tasadollar { get; set; }
        public double factor { get; set; }
        public string fechaidsc { get; set; }
        public string fechafdsc { get; set; }
        public double descuento { get; set; }
        public double existencia { get; set; }
        public double reservado { get; set; }
        public double ordenado { get; set; }
        public double cntrma { get; set; }
        public double backorder { get; set; }
        public double cntminimo { get; set; }
        public double cntmaximo { get; set; }
        public string fecultcpra { get; set; }
        public DateTime fecultvta { get; set; }
        public string fecultord { get; set; }
        public double cntultcpra { get; set; }
        public double cntultvta { get; set; }
        public double cntultord { get; set; }
        public DateTime fecinicio { get; set; }
        public string feccierre { get; set; }
        public double cntinicial { get; set; }
        public int estatus { get; set; }
        public double comision { get; set; }
        public double disponible { get; set; }
        public string observacion { get; set; }
        public string almacen { get; set; }
        public string idcia { get; set; }
        public string moneda { get; set; }
        public double precmayor { get; set; }
        public string medid2 { get; set; }
        public string medid3 { get; set; }
        public string medid4 { get; set; }
        public string medid5 { get; set; }
        public double prcmed2 { get; set; }
        public double prcmed3 { get; set; }
        public double prcmed4 { get; set; }
        public double prcmed5 { get; set; }
        public string descrip1 { get; set; }
        public double framed2 { get; set; }
        public double framed3 { get; set; }
        public double framed4 { get; set; }
        public double framed5 { get; set; }
        public string medcpra { get; set; }
        public double fracpra { get; set; }
        public string fechamovi { get; set; }
        public string fotoid { get; set; }
        public int blimdsccnt { get; set; }
        public int bcntpuntos { get; set; }
        public int bcntx1 { get; set; }
        public double pordsccnt { get; set; }
        public float selectivo { get; set; }
        public double preciodollar { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string ano { get; set; }
        public string grupo { get; set; }
        public string tipopieza { get; set; }
        public float porcprc4 { get; set; }
        public float porcprc5 { get; set; }
        public string cta_inventario { get; set; }
        public string cta_ventas { get; set; }
        public string cta_dv_ventas { get; set; }
        public string cta_dv_compras { get; set; }
        public string cta_gst_comision { get; set; }
        public string cta_compras { get; set; }
        public string medida { get; set; }
        public string medidacompra { get; set; }
        public float comision2 { get; set; }
        public float comision3 { get; set; }
        public float comision4 { get; set; }
        public float comision5 { get; set; }
        public float comision6 { get; set; }
        public float calcular_prc0 { get; set; }
        public string ubicacion { get; set; }
        public float porcprc0 { get; set; }
        public float arancel { get; set; }
        public string idarancel { get; set; }
        public string fichatec01 { get; set; }
        public string fichatec02 { get; set; }
        public string fichatec03 { get; set; }
        public string fichatec04 { get; set; }
        public string fichatec05 { get; set; }
        public float precventaotro { get; set; }
        public string fechaupdate { get; set; }
        public string idoferta { get; set; }
    }
}
